Scoreboard:
  Header: "&6&lplay.Superbility.com"
  Lines:
    - " "
    - "&e&lParty: &6[Lvl. %party_level%]"
    - "&e- %party_member_1_name%"
    - "&e- %party_member_2_name%"
    - "&e- %party_member_3_name%"
    - "&e- %party_member_4%_name%"
Messages:
  ClanCreated: "&8Clan '&a%clan_name%&8' has been successfully created!"
  ClanNameExists: "&cA clan with the name '&a%clan_name%&c' already exists!"
  PlayerInClan: "&cYou are already in a clan!"
  PlayerJoinClan: "&6%player_name% &7has joined the clan! Say hello! &do/"
  DisbandConfirmation: "&6[&e!&6] &cYou have 30 seconds to re-type this command to disband the clan. &4[WARNING] THIS ACTION IS PERMANENT &6[&e!&6]"
  SuccessfullyDisbanded: "&aYou have successfully disbanded your clan!"
  ClanDisbanded: "&a%clan_name% has been disbanded :(. Good luck everyone!"
  PlayerNotInClan: "&cYou can't do this! You aren't in a clan!"
  DisbandTimeOut: "&cYou have run out of time to disband! Run the command again to re-try"
  PlayerInviteSent: "&aYou have sent an invite to %player_name%!"
  PlayerInviteReceived: "&aYou have received an invite from &6%player_name% &ato join &6%clan_name%&a!" #Will automatically add a click to join button at the end
  NoPermission: "&cYou don't have permission to run this command!"
  PlayerNotFound: "&cNo player with the name &6%player_name% &cwas found!"
  InviteExpired: "&cThe invite from &6%player_name% &cto join &6%clan_name% &chas expired!"
  SelfInvite: "&cYou can't invite yourself!"
  OtherPlayerInClan: "&cThis player is already in a clan!"
  ClanChatMessage: "&2&lCLAN &6%player_name% [%player_clan_tag%&6] &8>> &f%message%"
  PlayerAlreadyInvited: "&cThis player has already been invited to your clan!"
  NoInvite: "&cYou haven't been invited to this clan!"
  PlayerLeaveClan: "&6%player_name% &chas left the clan!"
  PlayerLeaveClanSelf: "&aYou have successfully left &6%clan_name%&a!"
  LeaderLeaveMessage: "&cYou can't leave your clan! Use '/clan disband' to delete the clan or '/clan transfer' to transfer ownership"
  LeaderPromoteMessage: "&cYou can't promote that player! Use '/clan transfer' to transfer ownership!"
  NoPermissionPromote: "&cYou can't promote that player!"
  NoPermissionDemote: "&cYou can't demote that player!"
  PlayerPromoted: "&aPlayer &6%player_promoted_name% &ahas been &dpromoted &afrom &6%player_clan_rank_old% &ato &6%player_clan_rank_new% &aby &6%player_promoter_name%"
  PlayerDemoted: "&aPlayer &6%player_demoted_name% &ahas been &ddemoted &afrom &6%player_clan_rank_old% &ato &6%player_clan_rank_new% &aby &6%player_demoter_name%"
  OtherPlayerNotInClan: "&cThis player isn't in a clan!"
  PlayerNotInSameClan: "&cThis player isn't in your clan!"
  TagWrongLength: "&cThe tag is the wrong length! It must be formatted like 'XYZ'"
  TagChange: "&6%player_name% &ahas set the clan tag to &6%clan_tag%"
  PlayerKickedClan: "&6%kicked_name% &ahas been kicked from the clan by &6%kicker_name%"
  PlayerKickedPlayer: "&aYou have been kicked from the clan by &6%kicker_name%"
  DescriptionUpdated: "&aThe clan's description has been updated by &6%player_name%"
  ClanListCommand:
    - "&b----------------------------------------------------"
    - "&6Clan Name: %clan_name%                              "
    - " "
    - "&2               =-= Clan Leader &2=-=                "
    - "%clan_leader%                                         "
    - "                                                      "
    - "&2                  =-= Elders =-=                    "
    - "%clan_elders%                                         "
    - "                                                      "
    - "&2                 =-= Officers =-=                   "
    - "%clan_officers%                                       "
    - "                                                      "
    - "&2                  =-= Members =-=                   "
    - "%clan_members%                                        "
    - "                                                      "
    - "&eTotal Members: &a%clan_members_total%               "
    - "&eOnline Members: &a%clan_members_online%             "
    - "&b----------------------------------------------------"
  ClanTags:
    LEADER: "&6L"
    ELDER: "&eE"
    OFFICER: "&fO"
    MEMBER: "&7M"